language: python

python:
  - "2.7"

install:
  - sudo apt-get update -qq
  - sudo apt-get -y install gettext libenchant-dev
  - pip install flake8 msgcheck

script:
  - flake8 weechat
  - msgcheck weechat/locale/*/LC_MESSAGES/django.po
